- packages/sdk/pureml/components/project.py
- packages/sdk/pureml/decorators/dataset.py
- packages/sdk/pureml/pipeline/data/create_pipeline.py
- packages/sdk/pureml/utils/pipeline.py
- packages/sdk/pyproject.toml
Bug fix
Height Link T-948
Close T-948
> 15 data lineage generation when no parents are given

- packages/sdk/pureml/pipeline/data/create_pipeline.py
Fixed the bug that was causing multiple edges between two nodes, when transformers are invoked multiple times in a for loop
Close T-980
> Multiple edges between two nodes

- packages/sdk/pureml/deploy/docker.py
> Activated building docker images without cache to utilize modified files

- packages/server/app.go
- packages/server/config/config.go
- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
Temporarily updated documentation URL
Need to figure out some way to make it variable generated from ENV instead
> Fixed documentation URL (Temporary)

- packages/server/app.go
- packages/server/config/config.go
> Fixed environment variables

- packages/server/config/config.go
- packages/server/datastore/dbmodels/common.go
- packages/server/datastore/dbmodels/dataset.go
- packages/server/datastore/dbmodels/model.go
- packages/server/datastore/dbmodels/user.go
- packages/server/datastore/impl/datastore.go
- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
- packages/server/middlewares/jwt_authenticate.go
- packages/server/service/create_dataset.go
- packages/server/service/create_model.go
- packages/server/service/get_orgs_for_user.go
- packages/server/service/user_login.go
> Fixed Postgres migration issues

- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
- packages/server/models/dataset.go
- packages/server/models/model.go
- packages/server/models/response.go
- packages/server/service/create_dataset.go
- packages/server/service/create_dataset_branch.go
- packages/server/service/create_model.go
- packages/server/service/create_model_branch.go
Close T-1161
Close T-1165
Close T-1167
Close T-1168
Close T-1167
Close T-1173
> Database UUID issue and Create branch issue fixed

- packages/server/datastore/datastore.go
- packages/server/datastore/dbmodels/dataset.go
- packages/server/datastore/dbmodels/model.go
- packages/server/datastore/impl/datastore.go
- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
- packages/server/service/get_profile.go
- packages/server/service/get_profile_by_handle.go
- packages/server/service/user_login.go
Public User handle API also fixed
Close T-1193
Close T-1194
> Dataset register issues fixed

- packages/sdk/pureml/components/auth.py
- packages/sdk/pureml/deploy/docker.py
- packages/sdk/pureml/deploy/fastapi.py
- packages/sdk/pureml/utils/deploy.py
- packages/sdk/pyproject.toml
Added type supports:
Input:
- pandas dataframe
- numpy ndarray
- text
- image
Output:
- pandas dataframe
- numpy ndarray
- text
- json serializable
> Type support for inputs and outputs for fastapi server

- packages/server/apis/service/org.go
- packages/server/daos/datastore/datastore.go
- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
- packages/server/middlewares/validate_org.go
- packages/server/models/dataset.go
- packages/server/models/model.go
- packages/server/models/org.go
Close T-1478
Close T-1481
Close T-1585
Close T-1480
Close T-1590
Close T-1521
Close T-1522
Close T-1550
> API Bug fixes

- packages/server/apis/service/org.go
- packages/server/apis/service/user_org.go
- packages/server/daos/daos.go
- packages/server/daos/datastore/datastore.go
- packages/server/docs/docs.go
- packages/server/docs/swagger.json
- packages/server/docs/swagger.yaml
- packages/server/models/org.go
- packages/server/models/user.go
> Org Join & Members APIs fixed

- packages/purebackend/apis/service/dataset_branch_version.go
- packages/purebackend/apis/service/model_branch_version.go
- packages/purebackend/apis/service/tests/user_org_test.go
- packages/purebackend/apis/service/user_org.go
- packages/purebackend/core/base.go
- packages/purebackend/daos/daos.go
- packages/purebackend/daos/datastore/datastore.go
- packages/purebackend/models/user.go
- packages/purebackend/tools/mailer/mailer.go
Close T-1667
Close T-1665
Close T-1698
> Email tls issue and user role update API

- packages/purebackend/apis/service/dataset_branch.go
- packages/purebackend/apis/service/dataset_branch_version.go
- packages/purebackend/apis/service/model_branch.go
- packages/purebackend/apis/service/model_branch_version.go
- packages/purebackend/apis/service/tests/dataset_branch_test.go
- packages/purebackend/apis/service/tests/model_branch_test.go
- packages/purebackend/apis/service/tests/user_test.go
- packages/purebackend/daos/datastore/datastore.go
- packages/purebackend/examples/prod/main.go
- packages/purebackend/tools/filesystem/filesystem_test.go
- packages/purebackend/tools/types/datetime_test.go
> Register dataset and model upload URL issue fix

- packages/purebackend/core/daos/daos.go
- packages/purebackend/core/daos/datastore/datastore.go
- packages/purebackend/dataset/api/service/dataset_logs.go
- packages/purebackend/dataset/api/service/handler.go
- packages/purebackend/dataset/api/tests/dataset_logs_test.go
- packages/purebackend/model/api/service/handler.go
- packages/purebackend/model/api/service/model_logs.go
- packages/purebackend/model/api/tests/model_logs_test.go
On review acceptance, logs are also migrated along with model/dataset version data
dataset_logs_tests ✅ 
model_logs_tests ✅ 
Close T-1942
Close T-1708
Close T-1703
> Review Api logs migration update & Log API tests

- packages/sdk/pureml/decorators/dataset.py
- packages/sdk/pureml/decorators/load_data.py
- packages/sdk/pureml/decorators/model.py
- packages/sdk/pureml/decorators/transformer.py
- packages/sdk/pureml/utils/pipeline.py
Removed name parameter from the transformer, load_data decorators. Added function name, and description in the configuration
> Removed name parameter from transformer, load_data decorators.

- packages/pureml_frontend/app/components/landingPage/Navbar.tsx
- packages/pureml_frontend/app/root.tsx
> centered hero content & added redirect to itself

- packages/pureml_frontend/app/routes/org/$orgId/datasets/$datasetId/versions/Pipeline.tsx
- packages/pureml_frontend/app/routes/org/$orgId/datasets/$datasetId/versions/customNode.tsx
> added custom node in data lineage

- packages/pureml_frontend/app/components/ComparisionTable.tsx
- packages/pureml_frontend/app/routes/org/$orgId/models/$modelId/versions/logs/index.tsx
Completed dynamic model version comparison.
> feat: Frontend comparisions improvement

- packages/pureml_frontend/app/components/ComparisionTable.tsx
- packages/pureml_frontend/app/routes/org/$orgId/models/$modelId/versions/$branchId.tsx
- packages/pureml_frontend/app/routes/org/$orgId/models/$modelId/versions/$branchId/logs/index.tsx
- packages/pureml_frontend/app/routes/org/$orgId/models/$modelId/versions/versionContext.ts
> Frontend extracting comparision sidebar

- packages/sdk/pureml/components/dataset.py
- packages/sdk/pureml/components/log/figure.py
- packages/sdk/pureml/components/log/metrics.py
- packages/sdk/pureml/components/log/params.py
- packages/sdk/pureml/components/log/pip_requirement.py
- packages/sdk/pureml/components/log/predict.py
- packages/sdk/pureml/components/log/resources.py
- packages/sdk/pureml/components/model.py
- packages/sdk/pureml/decorators/dataset.py
- packages/sdk/pureml/decorators/model.py
- packages/sdk/pureml/lineage/data/create_lineage.py
- packages/sdk/pureml/schema/__init__.py
- packages/sdk/pureml/schema/config.py
- packages/sdk/pureml/utils/config.py
- packages/sdk/pureml/utils/pipeline.py
1. Change URL for fetching models, datasets
2. Added description and time in data lineage with "desc" and "time" keys
3. Resetting local config when objects are registered
a. When a dataset is registered(in decorator), lineage components are removed from the local config at the end of the decorator
b. When a model is registered(in the decorator), the model entry is removed at the end of the decorator
c. When metrics, params, and figures are logged to a model version. Their entries are removed from the local config
4. Removed hard-coding of component keys from config creation
> Added description for lineage components, changed fetch urls, 

- changelog/components/core/navbar/index.tsx
This fixes issue #137 
Clicking on logo will now redirect to https://pureml.com/
> fixed navbar logo redirection

- packages/sdk/pureml/cli/auth.py
- packages/sdk/pureml/cli/helpers.py
- packages/sdk/pureml/cli/main.py
- packages/sdk/pureml/cli/orgs.py
- packages/sdk/pureml/cli/puremlconfig.py
- packages/sdk/pureml/cli/secrets.py
- packages/sdk/pureml/components/__init__.py
- packages/sdk/pureml/schema/backend.py
Added `pureml init` command to easily setup configuration file. Command has both interactive and silent options.
Configuration is stored in `puremlconfig.yml` file
Currently configuration file has 3 options (1 is commented for future)
- Repository (commented till storage migration)
- Backend_url
- Frontend_url
Made a genralized class for accessing the configuration data
Completes #180
> pureml init command and configuration file

- changelog/components/core/navbar/index.tsx
- packages/pureml_frontend/app/components/landingPage/Navbar.tsx
> fix: replace the 'github star' btn with custom github star btn

- packages/sdk/pureml/__init__.py
- packages/sdk/pureml/components/dataset.py
- packages/sdk/pureml/components/model.py
- packages/sdk/pureml/package/fastapi.py
- packages/sdk/pyproject.toml
Bug Fix: Fast Api server was fixed to take the runtime python version
> Fastapi python version

- packages/purebackend/auth/api/service/user.go
- packages/purebackend/auth/dbmodels/dbmodels.go
- packages/purebackend/auth/middlewares/jwt_authenticate.go
- packages/purebackend/auth/models/models.go
- packages/purebackend/core/daos/daos.go
- packages/purebackend/core/daos/datastore/datastore.go
- packages/purebackend/docs/docs.go
- packages/purebackend/docs/swagger.json
- packages/purebackend/docs/swagger.yaml
- packages/sdk/pureml/__init__.py
- packages/sdk/pureml/cli/auth.py
- packages/sdk/pureml/cli/helpers.py
- packages/sdk/pureml/cli/main.py
- packages/sdk/pureml/components/__init__.py
- packages/sdk/pureml/components/auth.py
- packages/sdk/pureml/package/fastapi.py
- packages/sdk/pureml/schema/env.py
- packages/sdk/pureml/utils/env.py
- packages/sdk/pyproject.toml
Fixes #228 
API changes made to support single API token instead of API ID and API key
API Token needs a unique name to be shown to user for identification
Tested locally using local backend and pip install local package
Pypi test package updates to 0.3.7
> Improved api token system

- packages/pureml_sveltekit/package-lock.json
- packages/pureml_sveltekit/package.json
- packages/pureml_sveltekit/src/app.html
- packages/pureml_sveltekit/src/lib/components/Navbar.svelte
- packages/pureml_sveltekit/src/lib/components/Tabbar.svelte
- packages/pureml_sveltekit/src/routes/+page.server.ts
- packages/pureml_sveltekit/src/routes/[username]/+page.svelte
- packages/pureml_sveltekit/src/routes/auth/signin/+page.svelte
- packages/pureml_sveltekit/src/routes/auth/signout/+page.server.ts
- packages/pureml_sveltekit/src/routes/auth/signout/+page.svelte
- packages/pureml_sveltekit/src/routes/auth/signup/+page.svelte
- packages/pureml_sveltekit/svelte.config.js
- packages/pureml_sveltekit/vite.config.ts
Added support for changing BASE_URL for frontend package for automatic builds and go ui package support
Env variable `VITE_BASE_URL=/_` sets the base url for the svelte config.paths.base which is used in all redirections as "{base}/your/path"
- https://kit.svelte.dev/docs/modules#$app-paths-base
- https://kit.svelte.dev/docs/configuration#paths
> Frontend base url for different build requirements setup
